FROM ros:noetic-ros-core

LABEL author="Christian Brommer <christian.brommer@aau.at>"
LABEL author="Martin Scheiber <martin.scheiber@aau.at>"
LABEL maintainer="Martin Scheiber <martin.scheiber@aau.at>"
LABEL description="CNS Flight Stack Test Environment (Noetic)"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install --no-install-recommends -y \
    vim \
    wget \
    doxygen \
    graphviz \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install --no-install-recommends -y \
    libeigen3-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libgeographic-dev \
    geographiclib-tools \
    && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install --no-install-recommends -y \
    python3-catkin-tools \
    python3-rosdep \
    ros-noetic-dynamic-reconfigure \
    ros-noetic-eigen-conversions \
    ros-noetic-tf \
    ros-noetic-tf2-ros \
    ros-noetic-tf2-eigen \
    ros-noetic-mavlink \
    ros-noetic-nodelet \
    ros-noetic-geographic-msgs \
    ros-noetic-angles \
    ros-noetic-diagnostic-updater \
    ros-noetic-urdf \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/flightstack
RUN wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh && \
    chmod +x install_geographiclib_datasets.sh
RUN ./install_geographiclib_datasets.sh

RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; rosdep init && rosdep update'

RUN mkdir -p /catkin_build_ws/src
WORKDIR /catkin_build_ws
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin init'
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin config --extend /opt/ros/noetic'
#RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin build'

RUN mkdir -p /catkin_make_ws/src
WORKDIR /catkin_make_ws
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin_init_workspace'


COPY ./docker_compilation_test.sh /
#CMD /docker_compilation_test.sh
