# Copyright (C) 2022 Martin Scheiber and Christian Brommer,
# Control of Networked Systems, University of Klagenfurt, Austria.
#
# All rights reserved.
#
# This software is licensed under the terms of the BSD-2-Clause-License with
# no commercial use allowed, the full terms of which are made available
# in the LICENSE file. No license in patents is granted.
#
# You can contact the author at <martin.scheiber@ieee.org> and
# <christian.brommer@ieee.org>.

FROM ros:noetic-ros-core

LABEL author="Christian Brommer <christian.brommer@ieee.org>"
LABEL author="Martin Scheiber <martin.scheiber@ieee.org>"
LABEL maintainer="Martin Scheiber <martin.scheiber@ieee.org>"
LABEL description="CNS Flight Stack Test Environment (Noetic)"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install --no-install-recommends -y \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/flightstack
COPY ./install_ros1_noetic_dependencies.sh /opt/flightstack/install_ros1_noetic_dependencies.sh
RUN /opt/flightstack/install_ros1_noetic_dependencies.sh

RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; rosdep init && rosdep update'
RUN mkdir -p /source

WORKDIR /catkin_build_ws/src/
RUN ln -s /source ./ext_source
WORKDIR /catkin_build_ws/
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin init'
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin config --extend /opt/ros/noetic'

WORKDIR /catkin_make_ws/src
RUN ln -s /source ./ext_source
RUN /bin/bash -c 'source /opt/ros/noetic/setup.sh; catkin_init_workspace'

# link scripts although not existent yet
RUN ln -s /source/flightstack/flightstack_scripts/launch_scripts/flightstack_op.sh /usr/bin/fs_op \
    && ln -s /source/flightstack/flightstack_scripts/launch_scripts/flightstack_dev1.sh /usr/bin/fs_dev1 \
    && ln -s /source/flightstack/flightstack_scripts/launch_scripts/flightstack_dev2.sh /usr/bin/fs_dev2 \
    && ln -s /source/flightstack/flightstack_scripts/launch_scripts/flightstack_remote.sh /usr/bin/fs_remote

COPY ./docker_compilation_test.sh /
#CMD /docker_compilation_test.sh

WORKDIR /catkin_build_ws
